keys:
  - &server_MGC-DRW-CTR01 age13tw3g5x7jd6svaldh57un0xjy65yhxrpau8kkjag2afml83c39wsqy8lvy
  - &server_MGC-DRW-SEM01 age1rd0y53lk5hxvwhay5gwx245yrcm8h57jppync6jf85r648xkaqksdey6nl
  - &server_MGC-DRW-PWS01 age1xwp7j76tekk4pxmylct87gkmfs90nq6alsz7u2w0grp54t5283hss9n66r
  - &server_MGC-DRW-FBR01 age1u9cf6kjq9qldjepengff8y9f8nf3vq47ksg7pn5ch4nu7arseyes2dc3g0
  - &server_MGC-DRW-BST01 age1l2zxenr383sdfwc4cyg8s4lqu8fxcj5amjanatv0f5r7w6ytus0qz0us3w
  - &server_MGC-DRW-HVS01 age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
  - &server_MGC-DRW-HVS03 age14tclpesd3fn0g073knxch6mt9syd06f85sl5gv5hjl3l42f92alq733v4d

creation_rules:
  - path_regex: sops/secrets/default.yaml
    key_groups:
    - age:
      - *server_MGC-DRW-CTR01
      - *server_MGC-DRW-SEM01
      - *server_MGC-DRW-PWS01
      - *server_MGC-DRW-FBR01
      - *server_MGC-DRW-BST01
      - *server_MGC-DRW-HVS01
      - *server_MGC-DRW-HVS03
