restic-repo-password: ENC[AES256_GCM,data:wDn4sp8W4lM=,iv:uDQ1Cvnw5N9+z5r9ddiW1N4ISDOkc4Wbpjir2JuD9FM=,tag:QSEXEzVawG97zlhr4/TZ+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age175y4g497fsz5x8slf3udhmvj5yw53ju2nsn4x9dzrkv5kh42995s0fvrmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQU8wbXpyM0NsT3ZnQkZZ
            d2YzUC9mWmwzMUJmWndNZmpmeDBGeXhnTms4CnpITjF1YktaVHJrRlRBVUNqQjlK
            L1RTTzFxUEdhY3RjeThUOHNZVkMySEUKLS0tIHRNSDl5aGR1SEpOUTRhb2NRSXdk
            WGZLRTJycEowekZMTVZjalNweWVPTTAKV0QoWIXctb8tcVJpYJp5qq+Vye3EUMh3
            IM1OTy74ZhJatrHSw4gT/fPmk40h2lXt2VtsWDuqyHudsEvOvwG7uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T05:51:47Z"
    mac: ENC[AES256_GCM,data:BBWWLLR/UMpwSkkKwAWf8Ezub5LJevCthm67PvcSU7WgpJOchA5KpaHU5eZQ5FZNfWyy8HQAzQg38tcuEYMf0KL4unKg+x2CvCfYczEdwAJBmMzDiDm9bADgRYAwdnOT+cW2lJJjFm3VBoqsdbnHMTiCxziC7Morr3DfzgwqZZU=,iv:a9C4X+M9ADOLZ2pWyPUYN4Qlz0njQ4YhJNENZSWUqTY=,tag:idsPdQtJkaRDoWEKv1HhCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
