semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
grub-admin-password: ENC[AES256_GCM,data:LYJEuFBhLzyetszAJjy1dZlKbGTkJoH65mRWScYgN+f1OVqYoErn9dpk0as0q/1tQvWo4CqCCLBAoD1PNxFOkLvaFLnDGOaoYxF7hfeMn5R1FD93nJVdfaFkOi9qeY1iU1v1VtnVB97cgmjcYYKdP0oGZQBjixKEAqrkTsOYdhkw2gP7TArE+s8HHb8ZBO1jPovW6mHbuajJ8rACYE57MJH7UQLB0l1y1wj0vSRwN9YlRxDY4RopkPUbzlmVburf5t1HXCWZ3WvHYZQPKzet6EdRy2qhKy6Z5enT5jTZlTofUb5DEaQKOSDXmhXrIP676sbWTgMMMT7WD8U0Q9WBYuf2UpvLS3B7+QjCn2djvkeCN7SLc9zXyymt,iv:3DgOe6pYZtAOaBiv5Vxcx+sVC+sHfUfBdVqPrxeLGEI=,tag:ZEANCAaFYDFyncvU0Eldtw==,type:str]
keycloak-db-password: ENC[AES256_GCM,data:Jzo5BiONxh3mc8llXhOgZYR+jt1L,iv:8JhQfiOCMKDn+W0CTxn1Ce0ki/kbe+c6oe5+MOQ2WPM=,tag:4dS83mD735Ypjcafg+7Qpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tw3g5x7jd6svaldh57un0xjy65yhxrpau8kkjag2afml83c39wsqy8lvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWm5CUDlzN20yQmtVb3BE
            WlRHSjU3Z3dHMkIyZ0xTSWFQWTZXUTdhS0FvClIvLzdML1hHcFF6MFFQaUVyb3JS
            cFhBcTAvakp3a290TUtjR2hYVmxVcU0KLS0tIDczRm5uOE1iQkQvS0FTampiUWl5
            NXRrZGhLREh1NmNBaHIrc3lmaHFrTjgKZB5P9Zg3//DbgL+7J/D+1X5TRunwHrb/
            RgVctthxp89eRdReX5RScK3IqQr5nkc/FD9mhbANn1hlFPOdULh1yQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rd0y53lk5hxvwhay5gwx245yrcm8h57jppync6jf85r648xkaqksdey6nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSODN2UkFpQmxtYys3WU03
            WEZuOFFxV25oK2tBSUtRZitPZ1JHYXdRaGlrCnVBeFg2cU5sRzFxOFFyY1k3SXdF
            THJNMzN4S1VoRDFrQkRsWGRRdGZRZWsKLS0tIDRDYXU3RVgvT3BpREloU3FHMFpF
            WnpVbW1tNDFpUkxPOHV4RnRzRm5ScnMKXv/Dzx7HUAwt+V1FSOrG6YJIwG1xcg9Q
            Q7cYlWD/QBBPNCUonZ8OUhinDuNggOV5zpIw+M/FHAgi426f8gxFbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xwp7j76tekk4pxmylct87gkmfs90nq6alsz7u2w0grp54t5283hss9n66r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVGhUb1ZMUlB6anZhTHRm
            d2FSci9BZGxoN0NLVXpPK3gybktubVlEYUI0Ci9YOEtEZTlTMnIyTU5YY05ja3Jn
            aC9kRVNyL0l2MHN4cGo4RWFMM2V4WU0KLS0tIEU1UTZ0REVIU1NQT0VQelRJVW1m
            RXFkRFQxdGVFL3JUVHkvaGlYSEREZlkKXgaUnLz2ae/T4wnXZ3TOZO7vWIuc0Sij
            FMkmTgO+h98sU9Ckqk/hdiqlIign+pg4j782JLLKT7M+8Jdc4uDSzA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u9cf6kjq9qldjepengff8y9f8nf3vq47ksg7pn5ch4nu7arseyes2dc3g0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVzBzTlIxMFhPQlR2amhw
            emxKOHJoMC83NWtlSCtpTDlDaHg0dG1wcVhnClVZMTNwTjM2VjBaQlRuYlQxWWFH
            RXU0cEZjOHRLTmV6bUlJNXNFUUxJYUkKLS0tIGZPUVg2NlNLZU5XTHUrUC81VU9w
            eG1aeU1RNXNsczhieFZhR3lFcHhsVXcKRgA0LZ/wWWZV9lPuvFMz4JWa3OPEm6WB
            QuFpUOgWd2NUcNm6dnBoNtqJxYdVJvzLJPHgAfQuccOytA0NZGb06A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l2zxenr383sdfwc4cyg8s4lqu8fxcj5amjanatv0f5r7w6ytus0qz0us3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5aXdCcktqNk03aU9vWmZQ
            TW1aVllJMVBrUjl6L3gzOXhMTnhNNUkvUlNNCkNkU0tETkdyL3pWbkNKOGR4YlpC
            WVFodXVnbnduNW00MkNuS1BsVGNzWTgKLS0tIGEwQ0VLRDF5WHFxajk3Zm1jbzhq
            bEI4cjNVQWw2Wk5nY3JMTWR2cG1JYnMKd00q/vRjj1ytonSHB96Veo+rzpgywHoi
            Y2fNTNmNbv5cSS4KKh7RTtT9RfcsHa0pAoXv/klYIhp/JUO85kHj6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sl4wge0wk4dkzsgx57mjft58mfc3wwvalvrvtqac7ct6l7tnafrsdgaevx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNjBZeXduMW15Tm5mQjF3
            TXZnaHBxTnJwbHpqWUQ2UjN6cGV0TnVpblgwCkIvaWNqekY0Qi9FSmRlSFhlUm03
            V3RvZmh0VVVGcUNCVkNudWhCVnFMNHcKLS0tIDlDdVVtTnVQU0szUTg1K0xnMmVF
            T2ttaGlCY2djNFoxYjR5U0ZDYWo3anMKCzBqCpNKHPby1uJGUaZfHh9RRZm95zhH
            +4TGm6JTpIgDfS8xATlEmAZaK9q7ZDA6J4ywh8qLjND2WUboDpY81A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-25T01:49:33Z"
    mac: ENC[AES256_GCM,data:Mdf9MkBd6gpTqIMb2Cpuv6kGCkzcW/xxvfd1KfXelN8jW9LWowQ7I0MS2arGbvfsay1EDETDUyYdvqNk3+ytcBjNR8awSL7pBhqWPoIxTTsD5xC91jbgizRmpDp6+vu9q9sOuhit3r8yHVuDlRBgbJzoG6S2RmOeoFhs/DAY2UQ=,iv:wotYW0fY4Om6Avn3tE8BzH966UC8+YqjjbNLsbezXp0=,tag:ykTTCkHel7qG3k58L6m2Sg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
