gitea-token: ENC[AES256_GCM,data:GWJRusqSNHaI+fAvPBmwuG93Qyi7s+9C9Ti29iKw6dylr6XtueKskZsHE86/ig==,iv:dzl6E4XkTiZMx4XWsx4kfvxIj8Jl4ov8xN+1Oe7+n4w=,tag:HAieACASluJx+HGSvKMRmg==,type:str]
restic-repo-password: ENC[AES256_GCM,data:bCHPHHC8X/av,iv:qh0fwbPgV1DALJM+wdogJVvFJvjd4RHfi4pw2ZxUhe8=,tag:7u37pGS9e6+9l63IMreInA==,type:str]
postgres-password: ENC[AES256_GCM,data:Zm6mUeHmKLxqtY5UY8DDztRkAy9bdBmmuobI/onNWq6/iuqi,iv:eP+AzeDhXUtr5scqQrBMBZeRCTlMDfEYan5s5uiv7D4=,tag:Y8XhQner6MfYmXhaFtvL4g==,type:str]
semaphore-db-pass: ENC[AES256_GCM,data:rl0h44EoMEJZxw5inGTriRzPONffrV4FI4exWOD7trufMoAf,iv:69/ePkEX+rngXBOmn2xxcm3DpeUUgLLc55bHmK8CigU=,tag:BPsiTF8mO4J25STVAAbtMQ==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:FIv1gVrzVCupMm74wNagRQrqjuBDTx8rHnqRsgO8ArjiPxV9Q+C5R03nnrrxkmh1sXDtjEJh4BPl5W5W3lvmROoWeTPG6Sg5Uafz0w==,iv:Tc1xyz42T3SPpTNd4SAdQpu9LDecbZY1CLA/ZZdDnrg=,tag:2dp1iMpGbI/7ySgnmBnH1g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t5m8rsa560r88nex0rwycxjkdfhr9z9xz6x7kymzvaewqfrfvqxsaqf67a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNVVNM0Jha3h1a3FQaTBX
            Zm4xVjZWTFA2N284dXVhSkhCVnZpWWV1dlhzCm9PYXIxUjFDcnRkQ2Npc1ljTUw3
            eTEwOUVJWTFMNU9QQVYwQlFWQ3Z6cXMKLS0tIEhxb3FuNGw0VnhwNEQxMFN2Wmdy
            ajcrQlFHL1lUR2labjVqNVNvWkpxOEEKsNM+3ACEBNZFRkmquB2G0e30T5qwmYgB
            3ya60ZHpwljS32FZdJdMD2AM6sSfumwEOoElNhvzWjfwNHgmHJt5lA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1suplh033nftdtj7krll4zp4r4v549c6wna2r6xlz4su9zjq9sfts4hrayk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NlMwa0JYdzZ3c3Izbys4
            VGxyVlN5cmlBcGUvRGF1TDhxQ0xrek01WlNrCklaNTl5MGE1aWtFU0g5SG15ZFJZ
            VnFiRmtnOVduZ3pHdndHc3I1QlNhVHMKLS0tIDBkektVcFFOL1lRdTF5amcyUmhK
            MGpXQm9XNXIrTWxBRGJUMjl4QWxwUVkKrcnPl8FfruejTD8eWocY5PoYeC9E5qHF
            Id/5AGbH37qn6THa0sRQbbjtqXM+fJm0X7ZqBik22kVG13jjcHoT0Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e7kxmnjk0ryjecz62g5u5lmufwfepth9fa44ld889x2gpsdcvc5sqfrlxq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4OGNsNDBzWm1IN1FMQTZh
            dXRKQ0o5QnlHc3RWQ2dhUkVWUkFjbGZFUGtRCjlFaFlpeTZzNE54VmYvQjZ4MWZK
            SVRnc0g3dFhzWi9zK1hLbDIzYVp4TmMKLS0tIHBOdkQxaWJLR0N2RUJIOW81Kzhj
            cjZJVDI0aXdUSDNjelBBOVRxRkovZG8KL4hjX8oAFYr9JMNHFBOvmE4r747qYzoQ
            HSt3TbDjPmsu2+7CvcOrKd2aJcACTm8TmLwBhs292ABIb+mAoVT6Kw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age158eqlx3gyrm92nhs87awg8xgd6rm7ujss80yavzjvglcskvdggest8tyry
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVDhRNFhRY2R2MnByU1Vq
            N0dNU2ZvYTI4QlVzL3E3aTRsQ3F5UUZYY0FnCkhwUmR0RDhYMXBuWXBVbTFmUFBp
            VWY5Tk9TUmFOR2taMFJsY3Rab29tVnMKLS0tIGhrZzJlbk50bTdxM1BVbGVlWlhI
            VnBkRnZob0MwcDhXdGxQWEw4RWFIMTgKlXCv8I1Dq95KWRRuKo0YCP7ki7MZHMwE
            hA2jMJQb0clCNZska8CrsQmNSRG8GT+rtc7vYDiBYeDglVxQlZ1NOQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jgmhgf4g4h7f3uj5rqanmj8ha8kwf2ukk707gecwc9msnq87n9mssc5h7h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUVnM5Uit2YmRLbnhWZHJI
            S2J0bFNWazBUMGViZmtBN25VaVJsaWtrQWtBCmI1Wmp0QURVQW1wakpzOWt0TjZT
            aHdYU2g4bTZNejRYWVNoQ3ppRXpvNFkKLS0tIHF4YjJ3RVB4aTNIamJHaU84RTdB
            b1dvdTBvd2RGMXV4aDNVUWJPd0pQVkkKsQb1TKqcwsw6OilFqVMj1N/5Za4ukbGQ
            N3WMEV2WiRgoF7+5FROGGmbZBBCJFXD4xtAU0FHFkgsBC3gOXOb5qQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1axz8g6j9t8rrtyphrrhwhp9fjpntttftjndwdq5regx2r3p8e3aswujypg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UDN6a1B2VGFDVkhkWWN5
            QmRGc29TVzUxenU0cEFDYWJLZ0lkd0gyQWhvCjdraXZhOXlnVkdZVVVvajlLYTA1
            dkFza2xyRlk1U2NqcVc4OHlMaHFXancKLS0tIGg2RElVTFEzTUJjSEpFRjNUU2xs
            WC9QK1NuZmZYWVlOZXB1VS90ek5rem8KaMXvOvFo2kGGkyGeHjj9NnScxyp/cpAW
            Ih70Xg+mEgj/KthPlZNsNr30L4/8GE7et12qT38XKctlD5ps6ZkKRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T02:19:01Z"
    mac: ENC[AES256_GCM,data:2+VSkFELWKPm70PqQAsCPNhDtU6ojM3FPY/YvWiRyc1/O7vj1ykDUIFt3ZWyy9u4qNaNXlm7EujF4rZuDqSOaYi92hkdMO+xajrkvigseg99bF1pBvSemxFyREe5JS9/gVhixdZFFjkLC+Y2Y6xLOoA5LTglBb4eOs+GdeYeXAk=,iv:yEXndC+IaSkMH5UP+A3b5VrQd96IfGjcxWfvUUW2se0=,tag:6DKE/t8G6vhwfju/yMDdrg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
