semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
grub-admin-password: ENC[AES256_GCM,data:LYJEuFBhLzyetszAJjy1dZlKbGTkJoH65mRWScYgN+f1OVqYoErn9dpk0as0q/1tQvWo4CqCCLBAoD1PNxFOkLvaFLnDGOaoYxF7hfeMn5R1FD93nJVdfaFkOi9qeY1iU1v1VtnVB97cgmjcYYKdP0oGZQBjixKEAqrkTsOYdhkw2gP7TArE+s8HHb8ZBO1jPovW6mHbuajJ8rACYE57MJH7UQLB0l1y1wj0vSRwN9YlRxDY4RopkPUbzlmVburf5t1HXCWZ3WvHYZQPKzet6EdRy2qhKy6Z5enT5jTZlTofUb5DEaQKOSDXmhXrIP676sbWTgMMMT7WD8U0Q9WBYuf2UpvLS3B7+QjCn2djvkeCN7SLc9zXyymt,iv:3DgOe6pYZtAOaBiv5Vxcx+sVC+sHfUfBdVqPrxeLGEI=,tag:ZEANCAaFYDFyncvU0Eldtw==,type:str]
keycloak-db-password: ENC[AES256_GCM,data:Jzo5BiONxh3mc8llXhOgZYR+jt1L,iv:8JhQfiOCMKDn+W0CTxn1Ce0ki/kbe+c6oe5+MOQ2WPM=,tag:4dS83mD735Ypjcafg+7Qpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tw3g5x7jd6svaldh57un0xjy65yhxrpau8kkjag2afml83c39wsqy8lvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc1lQbmtKa2RQVzZib3gz
            aW84OTJWdDUyWE1rc1M1L2M5RmZoQWhiekZRClM2MkdrZlR6THVDYVNuemd0Skla
            bnZPNVBqNXp0YTZyY2Y2QnpFMnRtMUUKLS0tIEJuYnhscE5NMEhhbDEzTkVtVkFJ
            WjNzQVlSNktEd2ltMTVUMHFtWlVHWDQK7xSTdl5ZLF8lE3xMdZVIAFYjxGKep8Lo
            QGC8Dqy9zivVvUANEt1g9cXMEyeNoc8ErGUsrl0fNEL2l2zTuAQY2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rd0y53lk5hxvwhay5gwx245yrcm8h57jppync6jf85r648xkaqksdey6nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrak1kWTBPTHJTWEhIS3d6
            bEJTYmZhSkFicHFTSmt5K2cxTXV2SHZtSmhzCkdDeEFiZTl2UGRkRGVSV0N3Zkw2
            MitHNVc4ZW9YMndBZEJ5ZkFWVU5Nc3MKLS0tIGZUUzhxQS9MY3VZa1R0bnFYeHlh
            bFV4MUZJVkd6SUo0cUFOOVdvRW5VaHcKyKXWzwGlChsuBoEmiRi06HLtfLuQNWFc
            UywGrF9uMS3TdSnX14FsW8ZQYi5xfkf0wN/B/pmAcbi+zoI3d3yvFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xwp7j76tekk4pxmylct87gkmfs90nq6alsz7u2w0grp54t5283hss9n66r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UG1GZk9DQUhzekc5UEVP
            cExkSU9OQVkwRXVTcXZjbTVWWDFpa2QzQ0I0CnVwNDBKVUNYdGxoclhaZWh2ZHhu
            YUlvVWFXZXlBNFBOZHp3RWxzTG1WZE0KLS0tIEcwR2t5eGtoamVKWUxya1h2ck9V
            c0dzM08yaWNDWllHb2Z4emtxcUZySWMKMsOnqxO7RGOprKmI9wyAnTOZoc1+T2i3
            gRY6ns8RJd2L0Do7E+mFKFyG3EKCL6Qw0nC1wpaJHtUByamyz568oQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u9cf6kjq9qldjepengff8y9f8nf3vq47ksg7pn5ch4nu7arseyes2dc3g0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbCtsNVlhS05OT1VmYlp2
            bGdoblZsZ3NoRUViUVFjTE83V2FlU1hjNHhZCk9WblhYZDFPd2pya25BcXJTY0pT
            a3dNL1FKKzdRcUdSL2hoS1NGTDNodjgKLS0tIHRxeGcrSmVGVlZrOWtxMC9jeG56
            WkNhOHJSUml4THlUVzBaVmZHbFVGblkKRTdVJRLd8tPu1Xwav1WBN3vm0ILnRvuB
            JdMsHlEmLXTyTQk3rHHIT08ZqSov8QNC7MuMOQDq2/qRsECs+rk4Bg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l2zxenr383sdfwc4cyg8s4lqu8fxcj5amjanatv0f5r7w6ytus0qz0us3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVml6clVwL2VDeDBKUzRm
            b2NNZXNvdTRRRzlIQzRnQU4yeDlMV01KWFFrClRaUVlKc1U2Z1RTUllSMzE1U0ZJ
            U2R5WUlsNjA5ajhVRVVHc3VQN1Q2MGMKLS0tIG8zUThpUElMZTA5T0NrejJXcXVR
            TTJTY1A1L2UzcVhwV0FvNkw1ZUdyR28KXwcreSocUu6nCgiNdgH/kGEZBEgHHIiD
            Wkc97uJFmda3rYE6cFkDSYjlj9lJoCLCCfIZ6gq6sADyEGdq+WWpaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sl4wge0wk4dkzsgx57mjft58mfc3wwvalvrvtqac7ct6l7tnafrsdgaevx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQnFGRGZTOWErSUhnSzYz
            Nnh3bEp0M3ZyNFdDb0NGcUxISUQ5cTQ5WUZFCnI1N1lCbW1RUTVhSTZjV1NrVEVl
            Y0NMUDNjd00wNmIwNk9zZWVqN0pFQTAKLS0tIFh4ZEU2Q2dBamNiVXpURWFUU2k2
            eXZwcVk4ejcrb3ZKeDE4V3Awa0VJaUEKnSqRfUdW+/vuBlDWmxMlCSLyeJAvGO7j
            q/m5tXJ7T2NdcdZvd3K++qKf5V4+cbTrWS0MfcijCYH8z7qxVK0kHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxOElpMytISlh2Ui9WK0gz
            VG1HQUh3TUgza0pWaWs3OEljZ01VLzZneDIwCjZUVFFIU29QNGJIR0RkVTMxK1ly
            RW5Md2wvT2tWMk1ORTh3cisrYWlkMHMKLS0tIE1FdC9SYzlkVFNQTWVvaGEwRmJN
            Y2ZEYTZKU1ZRcndnYngzZkxFZnV4VTgKWiES6KM79hN+pK5v9exzQJucsA9ojTU1
            cpYZdPetPdPiqNzdjlxJckc+P0e9rfFbawKYREqkYmB7hB8xLdTFnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-25T01:49:33Z"
    mac: ENC[AES256_GCM,data:Mdf9MkBd6gpTqIMb2Cpuv6kGCkzcW/xxvfd1KfXelN8jW9LWowQ7I0MS2arGbvfsay1EDETDUyYdvqNk3+ytcBjNR8awSL7pBhqWPoIxTTsD5xC91jbgizRmpDp6+vu9q9sOuhit3r8yHVuDlRBgbJzoG6S2RmOeoFhs/DAY2UQ=,iv:wotYW0fY4Om6Avn3tE8BzH966UC8+YqjjbNLsbezXp0=,tag:ykTTCkHel7qG3k58L6m2Sg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
