semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
grub-admin-password: ENC[AES256_GCM,data:LYJEuFBhLzyetszAJjy1dZlKbGTkJoH65mRWScYgN+f1OVqYoErn9dpk0as0q/1tQvWo4CqCCLBAoD1PNxFOkLvaFLnDGOaoYxF7hfeMn5R1FD93nJVdfaFkOi9qeY1iU1v1VtnVB97cgmjcYYKdP0oGZQBjixKEAqrkTsOYdhkw2gP7TArE+s8HHb8ZBO1jPovW6mHbuajJ8rACYE57MJH7UQLB0l1y1wj0vSRwN9YlRxDY4RopkPUbzlmVburf5t1HXCWZ3WvHYZQPKzet6EdRy2qhKy6Z5enT5jTZlTofUb5DEaQKOSDXmhXrIP676sbWTgMMMT7WD8U0Q9WBYuf2UpvLS3B7+QjCn2djvkeCN7SLc9zXyymt,iv:3DgOe6pYZtAOaBiv5Vxcx+sVC+sHfUfBdVqPrxeLGEI=,tag:ZEANCAaFYDFyncvU0Eldtw==,type:str]
keycloak-db-password: ENC[AES256_GCM,data:Jzo5BiONxh3mc8llXhOgZYR+jt1L,iv:8JhQfiOCMKDn+W0CTxn1Ce0ki/kbe+c6oe5+MOQ2WPM=,tag:4dS83mD735Ypjcafg+7Qpw==,type:str]
olcRootPW: ENC[AES256_GCM,data:4tkgsmEL,iv:JzMSafmZva8fy7IUh0VtO4NoVMz+AJD3VgpiXdHT4po=,tag:LeMCdALNyIPLhzhHChs+Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tw3g5x7jd6svaldh57un0xjy65yhxrpau8kkjag2afml83c39wsqy8lvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeWpmQ1FwaTZLUHNEajVP
            dEhiSXBZK25MN2IvbXppOWZwaFZTVjBickgwClhvZ3ppR3VYK3htMVRVOEo1cTRZ
            WDRDRzFQMUhORExqbSt6Z2ZWUVBqRVEKLS0tIGljWnlIR2NtcVcvQlBDSlVxYTFM
            SmF6THZxSXM0L0FDYTVweFN0ZjladlEKYhWerM90geiXYEPmjxUMR+zhcBrByHxW
            GPRAIcERGTNtz8UKKjP29/SQIpKzeo7RMX1Cs5+yK4XQQmw+fY0mgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13ycsdrpwydpw89ae5tpmmwzwplgs2ne20k9ypyvknpz6faya7evquq4nmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNDdSN3dZUUZtZEx2Z25E
            b1hXWWQrQkxJQUpOc0J5VVNGVnhFQnVmeHpjCndJd2VwcjlqRnhzanZoUm1wWkh6
            dTQzNEZBZUE1MU5qNHlodVMvTThnbjAKLS0tIG5OczBuOGRVb1RUZ0FTSS8yVXgz
            WkN1S0trYUVBa3BXazAxTmdXVHNCREkKfiKhQFQxkGqmaRzfVZbsvdxTGzkcjgeU
            JaIT6/sQkEmmlo63g7tWrYK5/W6NPjKbweCtPCWWnluN9mYJEE+27Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rd0y53lk5hxvwhay5gwx245yrcm8h57jppync6jf85r648xkaqksdey6nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydVBGK0VsODFkZjRSeTlB
            dzhFS3pPMU9Qd1plZ2VNb0ZkQ0VrdHl3NzNFCmlrdC85SDIrOEhpeXRDZEFSaXVo
            SWFYbkhtc05tT2pmQTFPZ1BoaktlS2sKLS0tIEVWcUoxdUo3dFVsTml0VGpNQnA4
            RWkyRS9mRFhxS1ZDMllHU3paWTI3RUUKfeNjg08qrJKbqGNe8kVPaql51koF+BD9
            p113Aq6mLkzKiDMFoPKxSYkcxAMajmPp/khDUXRfMxs/KdkPX8GR8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kldg9c698z3sup4z3uzj8ytmd7jh5k4l53s23pv3h6yk7mdn8u0szlqvm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMVpkMUpoeGlwZWNyWkVS
            VFhYUyt0RDdERGVjZVhOUXlPdWRXcXpDUVhjCmg3MGxlak43T2xMTHRmZ0l6NkIr
            ZTVEQ1NWbEwrTXFUTFVwa1JtZkZnMGMKLS0tIHk5NmNmZG5aTVlVbEQ1NXJsdDZ1
            UHdaS1Fmbjc3L0praVV4Tzh1eXNVYzQKz1ZmYrU8Cs6q/JNnvS04zrXwikhmRh8r
            u1TnAU3rC/GBkiqoWYvBF7qbKfT+Zl2xhIobQCuW2V9bks86zYboXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u9cf6kjq9qldjepengff8y9f8nf3vq47ksg7pn5ch4nu7arseyes2dc3g0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdjdGOHRFY0hZYkEyQmZh
            K292VmdrdElvamZpa0J2UUM1a2JlZnphQkZRCkN0S0JxUno3TERCZGp0U1FkaDUw
            OFJSSXRmSkJiQlYxNUJaK2pyT3ltUHcKLS0tIE5WVHpXTy9FaWJkNHRiUjYzQktC
            ZUtBT1NBOWpkbWo0b2FpZThkN2lWRWsKBhHZ32VzbgSHHEvHk65dDyU2eDLiZSE/
            1Dgdvu2aDfBoZ1pTkOe5d8yjj/z4HpnzZWu4vXju+8S+jY6bAm9b/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l2zxenr383sdfwc4cyg8s4lqu8fxcj5amjanatv0f5r7w6ytus0qz0us3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNGhXdklpVkhVYXA0dTZP
            L1BnUms0Z2pyMVBUY1hiOXFpcVlITXMwVng4CjRDZTFQZlN6TGJuaEMvWmsrVlBi
            WWNsaElsamZJYlJMQjR5emd1b0VRVXMKLS0tIHdYZnZxTzk0dVRRS2R4QytXRkZu
            djBWd0hFdVhENjYzcWcyeG9kZVFack0K2+fhRZSJgaPkzBiYuEtkLFd1uRnN3pnu
            Yojxe0Pof8QP6e6EXOPRCqEAsVWVI9iT5Yrus6acSe0+B19Zv6PUrA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWWo4WkdwZTJ6T3ZsRkh1
            WGMybzZIaGxxZzh0L3lxMVhJR2krVjdQeEFRCkRkS2l1OGx4MXV5dHRSWE5qSE9U
            ZWtvbXcvZGd2YkFtUGNMQTBpWTBYeEEKLS0tIE5qd1dGMTluWUVIWUFRZUVnN1da
            ZWxWZE5BV3I0TlNEejBwdjZvQU5UVzAKX9oaUzDsQIv2kTp8UGjrtjDQ3gr0bDg5
            Gz9nix985KI7H7z94kyM917vctHEa2eVKTEctLTxWmAf7ORimaHrpw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14tclpesd3fn0g073knxch6mt9syd06f85sl5gv5hjl3l42f92alq733v4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpY2hkTC95b3NpQUt2Y1lE
            SEFTbDFKdXlkSXNaRk9XR1JtSnI2amlzNW5NCmFPbEQrLzh0dTFZRWxWWHV1TVRo
            dFREdnN2QjlFTjVaNHc4OVpsOXczRzgKLS0tIHVobW9oZmpqbTlOb1hWMWx1NXcx
            TVB6WXNORktNandFSzZDbHlXZCtxSEkK8iAmcPUDsWosSsUW2qTVJTkwvB8pWO6K
            M6voD0EVkpdsmxhS6rE4MrQZ3VmU3UJfWVrmQhSDZMQnNXaM9sM5Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-24T01:58:00Z"
    mac: ENC[AES256_GCM,data:rSouebhMylliiiYyx9RYxWueXrdoRMb5jVj/lXV5voBBUQzLqDBL/YmcowqBhVrkh5fTmaUw0KigPYcPOQxKMt5cqqIcoX5eJjEYf5tezuogt1kS3Fmm859Jr6zEuDIbVMrZZBTym+Y1qUT9EeXkcvTHIZzV+35RLIgrPZP9NMk=,iv:Q3sWcWEGruPkj6TKT5s7WRY3d+M+9fOGSZU5e3NzxLE=,tag:+iRKY0+naVbJq9TFdJlk9A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
