semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
grub-admin-password: ENC[AES256_GCM,data:LYJEuFBhLzyetszAJjy1dZlKbGTkJoH65mRWScYgN+f1OVqYoErn9dpk0as0q/1tQvWo4CqCCLBAoD1PNxFOkLvaFLnDGOaoYxF7hfeMn5R1FD93nJVdfaFkOi9qeY1iU1v1VtnVB97cgmjcYYKdP0oGZQBjixKEAqrkTsOYdhkw2gP7TArE+s8HHb8ZBO1jPovW6mHbuajJ8rACYE57MJH7UQLB0l1y1wj0vSRwN9YlRxDY4RopkPUbzlmVburf5t1HXCWZ3WvHYZQPKzet6EdRy2qhKy6Z5enT5jTZlTofUb5DEaQKOSDXmhXrIP676sbWTgMMMT7WD8U0Q9WBYuf2UpvLS3B7+QjCn2djvkeCN7SLc9zXyymt,iv:3DgOe6pYZtAOaBiv5Vxcx+sVC+sHfUfBdVqPrxeLGEI=,tag:ZEANCAaFYDFyncvU0Eldtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tw3g5x7jd6svaldh57un0xjy65yhxrpau8kkjag2afml83c39wsqy8lvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N2FYTno0ZmpmWjJ5ZW5o
            WXhaTnhlUStPZjVYaVNsVGoyeWdYNzYxWHdFCjJXcUtPYytYNGpLeklmUGI0NDVm
            bmcyMGx6OFJ1QnZVYmZDM211ZTZDcFEKLS0tIE1HY0Y5RjA2TmZ4Ly9Ba293ODBz
            aU5uVDByQnQyVEtManUyTUF0YURoSTgKitv+2WkJPIFv+qmtgcKG5DD+1aJKQNbO
            YnW0g4lrS6+ZRwbsjofH5qwey0qDmb/BJowmqEzxTE9oBN3Ds+MnjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rd0y53lk5hxvwhay5gwx245yrcm8h57jppync6jf85r648xkaqksdey6nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYzhKMHNGUStsZ1dkSUFk
            SUgrcG51Z0lManpKd1RUUnkySjY2UC80NDBnCnk3RDNLUW0yd1FYOXlEbUhxd0VR
            UEs1K0xFNldLL2lGU1ZqOEFJbm9zbGMKLS0tIFJrRmxCdWl0YzJINnllOEZyaTVE
            T0l4KzQxSFZtT1VxSTRoeSs5bjI0amcK56B904ob1oYHR3jaSEGn8Chmz4gSUwiO
            k+fWkuVdjVzS5BqzL39P2RoRc8INzoRwJSc8PPsH/WJzMH6/RboJow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xwp7j76tekk4pxmylct87gkmfs90nq6alsz7u2w0grp54t5283hss9n66r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDV1pYTk9sYWhEM2tvdUdL
            S1FsWjBneG9mYXo0RjMyRWQzSW04VWovdkJJCk1ocVd4dVpXWFp4djF1RDVjYUxD
            cXRmUFA4YThHV2hUejc5d1lUeWVYVVkKLS0tIGNQUGU2YmRzRUlrYkdpNlVxWkNB
            ZEIrZGxIa3QwaUNXTjJDWHp2NW8xMEEK+Jc25RPgXMvcyysZWoDmqhtxbtIgYlAR
            Awn0kTufktE6IYY+/ZrEabVZ37OBjT9mblbUyLE08eTCqr0G15Y3LA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u9cf6kjq9qldjepengff8y9f8nf3vq47ksg7pn5ch4nu7arseyes2dc3g0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdzhhM09oODlBZG9ZbFIx
            U1d6TjdSTXhZRzBTcVlzcXR0MnlhNWZUWmhvClZYQTlQakJkUWRBbmh2WTFZM0JR
            SGt4RVI0S3RYTnRKYkRMRDVyRDlMQ3MKLS0tIFJjT1NPRUtqWWVSN3B5Wm5OSHZC
            MkdCT0N1TEJZOXY3QTlEa0RqdjVaMEEKE7PLpiNiBl+NFBIB8QvlWkgICRJCpuI0
            CYhYa8s55RyXp+byh3QJhcqP4w7713xrjy5LL8m+KyNP4x4eBGqkEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15crdhuawrkt9g3ae45pz6ta74949j28gge42l99sl3q59kp2m3qs9678vc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaUV5K3J3VzVBMDBwTCtF
            VFdHS0ttRG9QUG5pYUFBc1h4NGkzTVVKZlRRCjJ1Mk5QdnJ1MXZWVmkzeTJaUVRW
            YWkxTERjRXdzYmFxMlhJWk9NMjkwcEUKLS0tIHdRL0ZuOVBKcTJNVVFZWG1xTmtS
            UFVlM2xzN3plS01ZV2tlTXJyUVNkN0UKVex8DJMxTfxn7p4qClveIzArJZEqNqbl
            CHiWTWOPy9oJWaJXveDMvOUYaWUK6vFqovl2W0Dbn0w/17Orv6JTSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1sl4wge0wk4dkzsgx57mjft58mfc3wwvalvrvtqac7ct6l7tnafrsdgaevx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWkltSlZIaG1xczVtd0JE
            VjFFYVRQd0RIdk1STW80YTJQYmY0cTc3VUdjCjBWQUN5NXVsK1RyWVI1dlE2WmUv
            eUVnOXB2dHhQMWt2R1ZXRTNpNDlEWE0KLS0tIHlPbUkvMldxalZCRFNVYW9EZWkw
            Q3p4RFpjby9mTmhMckNzMjlOOVRqYjAKEbcPtCCv5qyL/imF1uBJnsJT643y+i8Q
            uWD/j7Qhiyp3yGfk7C7p5jYe/54ebDMsEbwJ8uy3nTAFjS6tdWeeFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-08T13:34:17Z"
    mac: ENC[AES256_GCM,data:TwBNOzaoMRq8E/z3bRK+DCWQXYZsmP4CHAFYaEVNkmkLu22U/l74scMrf/D/bXA9wmE4midZb+wa7xdt11/NBUw8O2Ga6V7W9b6SnuMd2rtY0ofmf632TWjUrikIK1DFbGxj/r17XlsB1Uu0Oa27cetZ6dAfQhHdYWRJK9oPcPM=,iv:2sc8VPQoh1vvT+Dj0NiCo3rfLtpQkpyMYNkENHgkMfQ=,tag:AEwPt9gH3a6yidP69m6JTg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
