semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
grub-admin-password: ENC[AES256_GCM,data:LYJEuFBhLzyetszAJjy1dZlKbGTkJoH65mRWScYgN+f1OVqYoErn9dpk0as0q/1tQvWo4CqCCLBAoD1PNxFOkLvaFLnDGOaoYxF7hfeMn5R1FD93nJVdfaFkOi9qeY1iU1v1VtnVB97cgmjcYYKdP0oGZQBjixKEAqrkTsOYdhkw2gP7TArE+s8HHb8ZBO1jPovW6mHbuajJ8rACYE57MJH7UQLB0l1y1wj0vSRwN9YlRxDY4RopkPUbzlmVburf5t1HXCWZ3WvHYZQPKzet6EdRy2qhKy6Z5enT5jTZlTofUb5DEaQKOSDXmhXrIP676sbWTgMMMT7WD8U0Q9WBYuf2UpvLS3B7+QjCn2djvkeCN7SLc9zXyymt,iv:3DgOe6pYZtAOaBiv5Vxcx+sVC+sHfUfBdVqPrxeLGEI=,tag:ZEANCAaFYDFyncvU0Eldtw==,type:str]
keycloak-db-password: ENC[AES256_GCM,data:Jzo5BiONxh3mc8llXhOgZYR+jt1L,iv:8JhQfiOCMKDn+W0CTxn1Ce0ki/kbe+c6oe5+MOQ2WPM=,tag:4dS83mD735Ypjcafg+7Qpw==,type:str]
olcRootPW: ENC[AES256_GCM,data:4tkgsmEL,iv:JzMSafmZva8fy7IUh0VtO4NoVMz+AJD3VgpiXdHT4po=,tag:LeMCdALNyIPLhzhHChs+Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tw3g5x7jd6svaldh57un0xjy65yhxrpau8kkjag2afml83c39wsqy8lvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbGEwcFpYQXMxTlNwSVly
            dzlZNWlUbUJ2dGZMVTh5YmltanpUM0YwcjBNCjBxb0ZTdEhiNzBvOFpsODI4N0ZW
            NkNZUnVVQ1RmQ0ZCYTR0cTlmZ2hGZWcKLS0tIFVUWG5uUW0vVHZMelozMWtrRytB
            SVRxNFlzOTRqb1VQaEN2ODZ5blgwSm8KzZWyxfyzV0W1d2hxXgssJOY25PRZyk4h
            u55UPkWlyAWOg/ZPYnOeGLBM30A1TP+FJTJ9ktz9Apz2q+j8AO/Tkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rd0y53lk5hxvwhay5gwx245yrcm8h57jppync6jf85r648xkaqksdey6nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhblJkQkhqT3dLUVJpQjZJ
            ME1nV2RYYm90WXkxNE1WWFVlNk1RekFpNEJJCnRWMWhWdmFYSGFwSVJYeXRxZnR2
            ZTJFUExEU0hnZG1GR3JtRExaNlJCdXcKLS0tIDFhMVRVTnFQaXpoSHZibGwvSDM2
            WGJFbmJ2ZkRDRzlVM2p6YVFQWVpaSFUKpro21pUvkwoMpjOaEje5sQmCNWzwiDs9
            T+nldvlqFKu8leqKEkAMVOw9LqlVTk5GDnZcOC3NBbPEz7hB+QjQlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kldg9c698z3sup4z3uzj8ytmd7jh5k4l53s23pv3h6yk7mdn8u0szlqvm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOFd6MmJ2MEdlSnp3SDY4
            OWhtYjQvaTdyaVlhUTdvVjlrV25zb1NsdEFFClkreEZOMFZhV213am9PbmM3WnFO
            VXJPclAyRjh4ZUc0NVBJNXZJYnorancKLS0tIHdKWm1uYW9jUnRzWVRNTGtNQmtM
            SHRTVWtBMmtvcHZyMGZJSXQyUVlyT00K9jhJg/d2sHAJI9jYSoBHcRRmjOw9zhu8
            JehOlFk901Dkf9EQDKYAC+0kBCz0578TR6bhwXCkJmkmtPONXYoxWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u9cf6kjq9qldjepengff8y9f8nf3vq47ksg7pn5ch4nu7arseyes2dc3g0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OGRwaXB2N1VSYUY4YlVI
            Q2VKUEtIR3VGWUliYVhUeTNnUkE3d2RpeEhRCmQveXR3WjJqNFhmU2JYWXNMOHd2
            SGJPNysySDdkSDhKNWducWhVYjhKTkkKLS0tIGpDWWp4Mko4eEZySXl6ZEtSRmN0
            YTBzQWpNemhnNmZYUjNPRVBYMlpwbDAKoPixBNnmp1xKJLqXMd7+OSvRVXDRxExY
            QjabKlISBqIrUye4Ur0jG80buWZV2frAt13opatfLtrP7O39b/so+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l2zxenr383sdfwc4cyg8s4lqu8fxcj5amjanatv0f5r7w6ytus0qz0us3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4em5UY1lmandBN2tBb3or
            cmh4ZWlzK3htWHZ4UHk1QzFMa1lYdG5paVhFClFYL1NSUEJCL0p2eDFxSit2VFRz
            cHdhZnpwcTlHa05pcmdxT29xaXVzQTgKLS0tIHlWZ2ZTS21mNmo4R2FhN3ZKQnN0
            Ukt6VEFiYTZSaGVXTUZBWVdJT0ZPazQKJEfcedOVCUBWNNyFd9pBj5e9Qv1H+xI5
            0RnBFD+u3dthsmOSgmaeYxHv46eb/N9mjQUmojCnBxa4ubjCB5DMKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTkZKYTRBWGxhaUlobUMz
            V05NWUFqaFVJclBiZ21zSTRtMWJUTXRaYkRnCkdlUWZRRmx4bmpxbGdZdndFQUR2
            eVdKT2xsMnhaM1Z4R1JOQVRIaURsOXMKLS0tIDlScGQ1ekN0cHEzcTgvdUVuMmo3
            UUxXbDVWYUkwZjJjQkUxTWtPMHJXN2MKzxOlVhsCpHYI+4t17kbQclP4m9aolJAv
            MNPFOmDSRaB8W6g278YeW0pGaYi2sA80SqpisHCSGfHxbkAfLvjHlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14tclpesd3fn0g073knxch6mt9syd06f85sl5gv5hjl3l42f92alq733v4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdFc1ZzRFcWlyZEFXWGRL
            R2ZJQm5MR1Rhd285czBuTFlsYjRWdStva0R3CkFlNEdseG8yWUp6RGJndUNaWkxL
            QjFKZEF6ajNJY1VBWk0zallydklrc3MKLS0tIHhQMlV4TkVWd01Db242Sy8vTzZO
            NGpxMS9zUGVBNVZuRXZrSWVSQ1dFckEK3akYxvIMPqZoy/1xmMlw9F8Vvkg2s6yT
            ucYuY3A965OSTgDkERJby+s53ngrsdDkCxKux9zeHQVJzOM/HMr4Gw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-24T01:58:00Z"
    mac: ENC[AES256_GCM,data:rSouebhMylliiiYyx9RYxWueXrdoRMb5jVj/lXV5voBBUQzLqDBL/YmcowqBhVrkh5fTmaUw0KigPYcPOQxKMt5cqqIcoX5eJjEYf5tezuogt1kS3Fmm859Jr6zEuDIbVMrZZBTym+Y1qUT9EeXkcvTHIZzV+35RLIgrPZP9NMk=,iv:Q3sWcWEGruPkj6TKT5s7WRY3d+M+9fOGSZU5e3NzxLE=,tag:+iRKY0+naVbJq9TFdJlk9A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
