semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
grub-admin-password: ENC[AES256_GCM,data:LYJEuFBhLzyetszAJjy1dZlKbGTkJoH65mRWScYgN+f1OVqYoErn9dpk0as0q/1tQvWo4CqCCLBAoD1PNxFOkLvaFLnDGOaoYxF7hfeMn5R1FD93nJVdfaFkOi9qeY1iU1v1VtnVB97cgmjcYYKdP0oGZQBjixKEAqrkTsOYdhkw2gP7TArE+s8HHb8ZBO1jPovW6mHbuajJ8rACYE57MJH7UQLB0l1y1wj0vSRwN9YlRxDY4RopkPUbzlmVburf5t1HXCWZ3WvHYZQPKzet6EdRy2qhKy6Z5enT5jTZlTofUb5DEaQKOSDXmhXrIP676sbWTgMMMT7WD8U0Q9WBYuf2UpvLS3B7+QjCn2djvkeCN7SLc9zXyymt,iv:3DgOe6pYZtAOaBiv5Vxcx+sVC+sHfUfBdVqPrxeLGEI=,tag:ZEANCAaFYDFyncvU0Eldtw==,type:str]
keycloak-db-password: ENC[AES256_GCM,data:Jzo5BiONxh3mc8llXhOgZYR+jt1L,iv:8JhQfiOCMKDn+W0CTxn1Ce0ki/kbe+c6oe5+MOQ2WPM=,tag:4dS83mD735Ypjcafg+7Qpw==,type:str]
olcRootPW: ENC[AES256_GCM,data:4tkgsmEL,iv:JzMSafmZva8fy7IUh0VtO4NoVMz+AJD3VgpiXdHT4po=,tag:LeMCdALNyIPLhzhHChs+Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tw3g5x7jd6svaldh57un0xjy65yhxrpau8kkjag2afml83c39wsqy8lvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaU1Fdjc2ZjFDZUkxME5V
            akN0NDFHTGFENXNWVUR0M2JMVjQrMXFQRVJrCjdFTTJjenFtL0xnSTFEcVVmMkMr
            T1lxMVZ4YlJiS2FPc3gwVzZxTkJLS2sKLS0tIEt6a25JeHBKOEdNbjFnbVlmcUJS
            VWUyS285NTF3UnhoQm5BNXAxK2lIbEEKxXC5WKDSM5p3b5Ly12XIJYJYf1qg9F9h
            oTK1R+iRe+pgBWIhdXoVZuzLiroNkqhMJGE1cSPX6LAcKSXdAWRSYg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13ycsdrpwydpw89ae5tpmmwzwplgs2ne20k9ypyvknpz6faya7evquq4nmv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UFgzN04vM3JxNGRUelpF
            NlJXNjZCdmRMbEF2dElsQ0FOSi9GUTd6K1RnCmViaWdwOHh6SGFuakE2S3dBZkN4
            dGhVdnJyRmQ0enhFZ09PblhaQXg5U2MKLS0tIElBQlp3UTR4aDNGTi9hbC9qcElZ
            UFBsRFEraytVc21RUHdvZFRtcVlqazQKXZ/fNksNbL/lJ1DBV4wCF3vjO/lbzqLD
            o33/G/0Q3pjHTmT965N/z2/H4x27DapHYlB10Ni1nbnQxZ93XYeU2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rd0y53lk5hxvwhay5gwx245yrcm8h57jppync6jf85r648xkaqksdey6nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RzZCeDdEdU9GS1hrRDgz
            S1ZBYjBaUmVSQklpMSt4Q0g0MEdmamxxcVVZCk9TWGNtZjJnY3Y3bHNWbEJWWUs5
            bXZuQ0kvc245SVgyMDR2bEI0WWd3VFkKLS0tIEpHbWwzOHFZQXdQUlBZNzRUenVQ
            eUo3b0VvUk00U29hL08wKzFRZzlSMGMK1s9/SEMBwWeaUEZWRZr9WjhTnjQMcFVu
            9uqMVynvrj4/lrbqN7HtATySTsuDj4efCz8H19GTnEcYQ2O08TVC7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1kldg9c698z3sup4z3uzj8ytmd7jh5k4l53s23pv3h6yk7mdn8u0szlqvm4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubC8xYnJCQytlVnFUUDlT
            UE9pS3BTM2pOMHBQaUtxa2lxYksrVVA4WmpFClg5Y1NnOTViVXN6dzZxTk4wWUto
            U1g2M01oT2hpcmRUcTdsWG5xaVRocVkKLS0tIE5vWE1Mb3Z6OS94WTJXcStOSjkz
            cjNYK3YwN01XbytsN1M3M2lFNUZHYlkKRbZ+X9fNlzsUzk5wqezAynb0FUUIWq4K
            L4o7Cfiu7FeGwVkpaasbs4vXrRC/ffTvyC64yh6Lyb/uxR8EF64+ZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u9cf6kjq9qldjepengff8y9f8nf3vq47ksg7pn5ch4nu7arseyes2dc3g0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaHlxRCt0alhNL24ycGND
            SXpSdjN2ZURZUlpET3lJc2k5eWk3TUsrREM0CmpjSDhtdmoyY1VjcXZQSThYUXRN
            OE16eU52SHJSazJCaEUrTWhPZnl6c2cKLS0tIFhpMmZUbkF3QlZhRXgzOGxPakFn
            dGtlM1Q2eitjYld4cHBKQjRVblhzQjAKojN3Bdt7MCsew7lLnxV0LCSJIHJMLki4
            XXHidtzYHUD/pKuhYbsYFjDjS0Y1QA9pNtfCwnxJmGLn7g3qRaa1HQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age174jz0vs3zs06ck59krz3qazrszr8lnst4w8h4shmdj8ccaur84dsea6fkr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRVErM2lZY0N6WHYvdm03
            L2NFM3p4OGNST0xrSjBEd1ZzUFZWK3l4elJnClJiV1NadXBtTVJLVzZkQVlBb0Uv
            dVNlb0NZTHllVmI2Z0xyamh2dS9DMUkKLS0tIDFsN2gwclBTSWMrejVSWFcra1Zj
            TWt0UFpTb1dhOFlodmEraTZ0OGF5d1EKiwCwbjW9MqbIubQoKKLCKo4pg7yEJC6n
            JNC/Z/Ip3F4HFMDYNUVRvvCoF0Tl4dWfTF2LdD+EPdZL6YTxFMM6BA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeThuV05NalEvR0g4WEhv
            OHJRMEdQN2NOZkxFUkJhZjJSZldRNk5ZK0dBCmxhU05ZZWpMckpzT0ptU05PL1ZQ
            enFUZE1BODl5RHBycTRGdVIycHNHVlEKLS0tIE9DaFZlTjEyVjRsZk4vZ1VtQXlS
            ZVZ2cldCL1VqVzZERHdjRm1naEVNL1kKN/8ZHinVvtfDwSsik2/47o4bUJ2zUW+x
            yWPYvi4R8FugpsIGTbNnAz1gRzy4DmQo0cW+dzbuX8hVVswPw4eAHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14tclpesd3fn0g073knxch6mt9syd06f85sl5gv5hjl3l42f92alq733v4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpczZ0OGFIVmc0Qnc4Y0pJ
            WCtFVERhTFNlM2VtMDV1aVMrRFJSWlhDYzJNCk1WRDdTQTQ0S1hqNVFobEtlRHVF
            T29IMGRNcVlnbFJEKy9ad1FCaFJCNk0KLS0tIFUvZlRpMjB0VlNqZU9jWk5MRXBm
            ZldpN0dsZDhOTVJUUTNyMUpDRDJCd28Kf71A3nvCurax7srzwruFq/ITkhEPhHrm
            VgYx+6W5Z/bI8jv3qz7NNpvnOR0O/pYCcC9Y8pP24Ee0WbTl+k6Wyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-24T01:58:00Z"
    mac: ENC[AES256_GCM,data:rSouebhMylliiiYyx9RYxWueXrdoRMb5jVj/lXV5voBBUQzLqDBL/YmcowqBhVrkh5fTmaUw0KigPYcPOQxKMt5cqqIcoX5eJjEYf5tezuogt1kS3Fmm859Jr6zEuDIbVMrZZBTym+Y1qUT9EeXkcvTHIZzV+35RLIgrPZP9NMk=,iv:Q3sWcWEGruPkj6TKT5s7WRY3d+M+9fOGSZU5e3NzxLE=,tag:+iRKY0+naVbJq9TFdJlk9A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
