semaphore-db-pass: ENC[AES256_GCM,data:bA56NSl8V0chPCofydnhAEeJEbv7fK0okeUziVbOyd760f07TUE=,iv:BVHLbJ3GYiZn4tw4Sy9ZbuIiBx3jQ05BF5GxMVnPxIA=,tag:AHu/H8V4r6jSuw9Tqnz0ug==,type:str]
postgres-password: ENC[AES256_GCM,data:pAe/0qnuoF8JwtmlOSPFA6eqJPwLH8SbYbHG25fRocpuYhUkNCI=,iv:VsysBnQHOOnFGnmvoI2ix9BiKj5cKHY6NmJgqv0y58w=,tag:P3GQAd0SIElOKfdOJGI7iw==,type:str]
semaphore-access-key-encryption: ENC[AES256_GCM,data:LPsg0WUG8OsULQ8RbhpHN8I0ooRcVTRWrTtJdhXc8R2nYqCqd1wEPiW45yLaJAp7jnYnn+TgiB24yNc9Kgk5iy6UaiMAcGIzedNRPg==,iv:aFjHts1mHMJfSS1cG1cw02DmwB73DOKOdeTfHgrnQyE=,tag:ecUfdj2dTN7kDUXLC8Jf0g==,type:str]
restic-repo-password: ENC[AES256_GCM,data:Dz9NM28ETzg=,iv:kKIBjnBIw3t+4+0EBO19jK4S/ao3B4V0o0i1TO/9ja8=,tag:y/2G5ui/eXbN9aayNwyJAQ==,type:str]
grub-admin-password: ENC[AES256_GCM,data:LYJEuFBhLzyetszAJjy1dZlKbGTkJoH65mRWScYgN+f1OVqYoErn9dpk0as0q/1tQvWo4CqCCLBAoD1PNxFOkLvaFLnDGOaoYxF7hfeMn5R1FD93nJVdfaFkOi9qeY1iU1v1VtnVB97cgmjcYYKdP0oGZQBjixKEAqrkTsOYdhkw2gP7TArE+s8HHb8ZBO1jPovW6mHbuajJ8rACYE57MJH7UQLB0l1y1wj0vSRwN9YlRxDY4RopkPUbzlmVburf5t1HXCWZ3WvHYZQPKzet6EdRy2qhKy6Z5enT5jTZlTofUb5DEaQKOSDXmhXrIP676sbWTgMMMT7WD8U0Q9WBYuf2UpvLS3B7+QjCn2djvkeCN7SLc9zXyymt,iv:3DgOe6pYZtAOaBiv5Vxcx+sVC+sHfUfBdVqPrxeLGEI=,tag:ZEANCAaFYDFyncvU0Eldtw==,type:str]
keycloak-db-password: ENC[AES256_GCM,data:Jzo5BiONxh3mc8llXhOgZYR+jt1L,iv:8JhQfiOCMKDn+W0CTxn1Ce0ki/kbe+c6oe5+MOQ2WPM=,tag:4dS83mD735Ypjcafg+7Qpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13tw3g5x7jd6svaldh57un0xjy65yhxrpau8kkjag2afml83c39wsqy8lvy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZHdnNXZQNEpRMmVaMnQw
            ajdOSmJGcTFaOXg0Y0NCOVlSeWtIbWwrY1FBCitVUnU4bUxPbS9Gck12Q1RjUXBW
            QVpWaHZram5LTDlLSFdyVGx1Z2RyUlkKLS0tIEUwSzR0L2F4SEFabEk3YzF1ZEJp
            eWsyZThianptalhCQmZYL1pUKzRQSkUKrzxlQE2eAIRgvds6ahlEC38J0TMkKCkC
            NXsPEpOtaKEaO4iSWNGy6FMmkDaAHjlor/zt+7e0+RrDaPDjjhdSmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1rd0y53lk5hxvwhay5gwx245yrcm8h57jppync6jf85r648xkaqksdey6nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbklUUzRqNzhxRGU3clFL
            c3N5VXJhVmNyQWFGSlNCY0pqRmw4MVNlN3hVClN2WFBDRWlzeUFZZVZlVDg1bW95
            Nk92OXptbWJPWTBRaDlwUWU3NVFmZTQKLS0tIDZoc1VuOW1pL3krWU54TXlLbjFT
            b0laY1ZKNXdHZEpCOVlPbTdpZ2pjbjgKPPc0RDIR2nj28P4DMOAXgousg//6tQg3
            pJqy2W2/F5ZeWKL2FR8Y7rRDRzfzBBgzHwXcQFZo5QYyNmjNhTFm0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xwp7j76tekk4pxmylct87gkmfs90nq6alsz7u2w0grp54t5283hss9n66r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTU1JlYWc5em50dmVsN1dK
            c3JaWWhYazN4UzZ0UzVQN2swSWhtUUg4N2gwCmdhcVAyeWpSc3FGTExIWEFGMEw0
            VUdidzAyblQyQmpWR0hPYXlVVGdkdkUKLS0tIHZKaFRYOUlHUU9QMDRqWHVyc2Ev
            WVVub2dLaTgzWmd4RzJHWjdCUjZ5QVEKiF/XZ9ijaRlpNpHki1Lnsf3ij8HCbt38
            cqCg/emy9hz1/kJAQRNGdyE8Am48PZf014PUzlFltVfs9ak4rl6i0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1u9cf6kjq9qldjepengff8y9f8nf3vq47ksg7pn5ch4nu7arseyes2dc3g0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcG1sbEhGaXpNVGpDRHJU
            SUNyWVdzMWhEOVhCMGFjamMxM3o4c0FjdFZBCkhaWlN0b0IvaXJiS0N0bVdHWG0x
            aDJtQXgrd3hsZ0VoallQSzJwUXNaVjgKLS0tIHZwUzR5bG10elZLVkI0MzlEdHp0
            NFNvNmdpSU14M2ZHazdNTXJsY3BvSmMKcdkUkcEwbi5yTXwBCBsZwHYW9cZx+1Y2
            8M/jSIlHtV7/8gq+wMBy1y7Q60WxknpDpH5yW3Gi509PzYAkeHcR9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l2zxenr383sdfwc4cyg8s4lqu8fxcj5amjanatv0f5r7w6ytus0qz0us3w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEaGhvVXFJejc2b0taMkM2
            RTdvTHh0TGtRRlJtWGNoRG9pNG1kc0FPRzJvCkUxN0V5cEJYNTIrWGFlb0s1V0NH
            Z0doZHRHNXl1alhzZzM5NGNHN1N0WnMKLS0tIGJKNHdscnlxNld6dnk2RjlnRFVX
            UHJucW9KcFRvY29vTEJEVHczTi9GOUkKIX2gfV+o1KK+OmaqGmrSdt+FCsuliJBC
            0NEb+p74hm/0TUiEwtC1GbWT7jbRTzKVeenKWZA5JkSBJqg1FQVHAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age103qqt3eacmhxestkspwqzrgaekzh6gmquuxa7djradah46zuzfkq6qhu7l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUnJPbFZ3VnhtOUJ3Sy81
            cldyZWd1N0xVWk5rMXV2aXBnL1dNK3pPRGhBCkFoTEh3WGtxaExXdXBkb2ZnQmNw
            c0FKRUJOa3hreHVUSm9UUHJJQmt0VW8KLS0tIFNTdm1wYXZXNGJwaVJLZjVWa1JY
            YUIwWlViMGVxa3duRnJ1ZXVwdTdTK28Kk59cbMB1OcwhY/UVccme8hpIzzzD8Y8C
            2FQhj3pnGXnLQnzdh1D7cEQKnMzTJ5LkcPAPgFMjTvYP4CjL/QFJmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14tclpesd3fn0g073knxch6mt9syd06f85sl5gv5hjl3l42f92alq733v4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWTJzSEpxUWRIVTZMRjdL
            R3QzRDlXOCtZT1h0NjZJVzI4NEtYUlpmdGdvCk5MelEwMnduczBGNU0vNVlwcEIy
            K2ZBaUU1QTd5YlZ4djhzcE5ybWhyYmMKLS0tIDQ3N0NNVG9lRGswcXYvdng0K0Vx
            SUVtTm8weXpwU3BvY0xvNWNmeVRMWDQKzcyzDY70YSVaxVaUzaWy7hxilf2vOD5T
            Hrl20IultcW0+09ZPt5K4kqtCXZTT0WDPQ60mMznjD+SIKtJo4FpYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-25T01:49:33Z"
    mac: ENC[AES256_GCM,data:Mdf9MkBd6gpTqIMb2Cpuv6kGCkzcW/xxvfd1KfXelN8jW9LWowQ7I0MS2arGbvfsay1EDETDUyYdvqNk3+ytcBjNR8awSL7pBhqWPoIxTTsD5xC91jbgizRmpDp6+vu9q9sOuhit3r8yHVuDlRBgbJzoG6S2RmOeoFhs/DAY2UQ=,iv:wotYW0fY4Om6Avn3tE8BzH966UC8+YqjjbNLsbezXp0=,tag:ykTTCkHel7qG3k58L6m2Sg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
