name: Deploy NixOS systems with Deploy-RS

on:
  workflow_call:
    inputs:
      hostname:
        description: 'Target hostname'
        required: true
        type: string

jobs:
  deploy-nixos:
    runs-on: MGC-DRS-01
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ gitea.repository }} repository has been cloned to the runner."
      - name: Run deploy-rs to provision ${{ inputs.hostname }}
        run: deploy .#${{ inputs.hostname }} -s
      - run: echo "This job's status is ${{ job.status }}."
